### PR TITLE
dcm2niix Exitstatus

### LINKED ISSUE #6: Gear should exit success with no output when no pixel data

### PR DESCRIPTION
**Pull request by lmperry**
Closes #6 

1. Gear is now aware of dcm2niix new exit status for non-images. 
2. Builds dcm2niix from source with openjpeg compression support

### CODE REVIEW

**Comment by lmperry** [comment]
@neurolabusc: In addition to handling the non-image DICOM series, this newer version handles one of the compressed DICOM series referenced in #4, but not another, which fails because of a vendor issue. Interestingly, when it fails it exits 0 (as shown below). 

```[scitran/dcm2niix]  running...
[scitran/dcm2niix]  Unzipping /flywheel/v0/input/dcm2niix_input/GRAPPA_DTI.dicom.zip
Chris Rorden's dcm2niiX version v1.0.20170724 (OpenJPEG build) GCC4.8.4 (64-bit Linux)
Found 1196 DICOM image(s)
Image Decompression is new: please validate conversions
Warning:  DICOM violation (contact vendor): compressed image without image fragments, assuming image offset defined by 0x7FE0,x0010
Warning:  DICOM violation (contact vendor): compressed image without image fragments, assuming image offset defined by 0x7FE0,x0010
Warning:  DICOM violation (contact vendor): compressed image without image fragments, assuming image offset defined by 0x7FE0,x0010

Error: OpenJPEG failed to read the header /flywheel/v0/input/dcm2niix_input/GRAPPA_DTI/IM-0156-0691.dcm
Conversion required 16.188093 seconds (8.668925 for core code).
[scitran/dcm2niix]  Success! Wrote:

root@8a61c024da7f:/flywheel/v0# echo $?
0```

**Comment by neurolabusc** [comment]
@lmperry - can you please send me an example of this image? It does sound like a vendor error, but worth checking. I guess a larger question is what response dcm2niix should generate if it processes some but not all of the DICOM files in a folder. I assume EXIT_SUCCESS should be reserved for situations where ALL images are processed, with other values when ANY of the images are problematic.

**Comment by neurolabusc** [comment]
@lmperry - can you see if the latest patch works. Your case is unusual, since the warning is set when reading the header, but the software decides to assume that the compressed image will start at 0x7FE0,x0010 instead of in the (required but not found) fragment. This kludge does seem to work with several datasets. However, it means the image is not rejected at the header reading stage. I would still like to see this example. 

As an aside, you mention the latest version DOES process one of your problematic examples, can you please verify that this image used transfer syntax 1.2.840.10008.1.2.5 (RLE). I did recently add support for this simple syntax, so it would be nice to hear that my new code works. While some argue that [RLE is almost useless for medical images](https://www.medicalconnections.co.uk/kb/Transfer_Syntax#RLE_Lossless), in my experience it has moderate success for images with >8 bit precision as the higher-order bytes change with low frequency. In any case, while I try to support compressed images I discourage their use: the DICOM standard does not require any tool to support these, so using compression often means many popular and valid tools become useless.

**Comment by lmperry** [comment]
@neurolabusc - The latest patch exists with exit status 1 on the dataset in question. I re-sent a download link for that dataset via email. For this dataset I can convert via dcm2niix if I first decompress the images with `gcdmconv`, which is the reason I added https://github.com/scitran-apps/dcm2niix/blob/exitstatus/run#L87-L111. 


For the dataset that does NOT convert: 
```
# gdcmdump IM-0156-0691.dcm | grep -i syntax
# Used TransferSyntax:
(0002,0010) UI [1.2.840.10008.1.2.4.90]                           # 22,1 Transfer Syntax UID
# Used TransferSyntax: 1.2.840.10008.1.2.4.90
```

For the dataset that DOES convert: 
```
# gdcmdump IM-0155-0013.dcm | grep -i syntax
# Used TransferSyntax:
(0002,0010) UI [1.2.840.10008.1.2.4.90]                           # 22,1 Transfer Syntax UID
# Used TransferSyntax: 1.2.840.10008.1.2.4.90
```

**Pull request merged**
