### PR TITLE
Parker dev2

### PR DESCRIPTION
**Pull request by dpark6060**
Why parker dev2 and not just parker dev?  To that, I say...Why not stop asking questions.

### CODE REVIEW

**Review by kalebdfischer — CHANGES_REQUESTED** [review]
It would be nice to have test(s) + test data and generally, it is a better practice to have `if __name__ == '__main__':` with testable functions, but "better" may be the enemy of done in this case. Especially since we're already a little janky with the bash here. I would add a couple of `# TODO:`s on fix_dcm_vols.py noting the need for tests and conversion to functions.

**Comment by kalebdfischer** [comment]
> It would be nice to have test(s) + test data and generally, it is a better practice to have `if __name__ == '__main__':` with testable functions, but "better" may be the enemy of done in this case. Especially since we're already a little janky with the bash here. I would add a couple of `# TODO:`s on fix_dcm_vols.py noting the need for tests and conversion to functions.

Basically, let's punt it to the poor soul who must modernize dcm2niix.

**Comment by dpark6060** [comment]
Yeah, I agree.  I actually didn't write fix_dcm_vols.py, it's a script written by the group.  At first I considered modifying it (for logging and debugging and general improvements), but decided it would be best to do a pull straight from a commit of theirs, for open source purposes or whatever.

**Comment by dpark6060** [comment]
I only included the py file so you could see it.  Otherwise the Dockerfile pulls it in.

**Pull request closed without merging**
